# Cấu hình Database H2 chạy tạm trên Render (để không bị lỗi kết nối SQL Server)
spring.datasource.url=jdbc:h2:mem:school;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Tự động tạo bảng dựa trên code Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# Cho phép truy cập console H2 nếu cần
spring.h2.console.enabled=true
